import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";


export const metadata = {
  title: "NextJs Coarse 1",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl" >

      <body className="font-EstedadLight text-TextColor my-5">
        <div className=" w-full m-auto pl-[50px] pr-[50px] min-h-[100vh] flex flex-col justify-between ">
        <Navbar />
        {children}
        <Footer />
        </div>

      </body>
    </html>
  );
}
