import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import AccountIcon from "@/components/navbar/AccountIcon";

export const metadata = {
  title: "NextJs Coarse 1",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body className="font-EstedadLight text-TextColor my-0 lg:my-5  lg:px-[50px]">
        <div className=" w-full m-auto min-h-[100vh] flex flex-col justify-between">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
